### ISSUE TITLE
RuntimeError: expected scalar type BFloat16 but found Float

### ISSUE THREAD

**Issue by mEbara** [hppRC/llm-lora-classification#1]
こんにちは。
以下のコードを回すと、以下のようなエラーコードが出ます。

コード: 
!poetry run python src/train.py --model_name rinna/japanese-gpt-neox-3.6b

エラーコード: 
RuntimeError: expected scalar type BFloat16 but found Float

使用環境としては、
・Google Colaboratory(GPU, A100 ハイメモリ)
・Python 3.10.6
・Poetry(1.5.1)

原因と対応方法についてご教授いただけますでしょうか。

**Comment by hppRC** [comment]
@mEbara 
こんにちは、本リポジトリのコードは `huggingface/accelerate`というライブラリを利用しているのですが、`accelerate`を利用してプログラムを実行することで、このエラーを解消できる可能性がありそうです。
具体的には、実行コマンドを少し変更して、以下のように実行してみていただけますでしょうか？

```
!poetry run accelerate launch src/train.py --model_name rinna/japanese-gpt-neox-3.6b
```

**Comment by mEbara** [comment]
早速のご回答ありがとうございます。ご教授いただいた方法で解決いたしました。

確認したところ、GPU A100(ハイメモリ)でのみ正常に動作しました。
Google Colaboratoryでは、accelerateのconfigをyamlファイルから手動で設定する必要があり、そこが少し難しかったです。

参考までにcolabのURLを添えておきます。
https://colab.research.google.com/drive/1nOzS5mH_ptoKPnMwqBmiohPPHaiAT8Op?usp=sharing

ご回答ありがとうございました。
